image:
  - Visual Studio 2019
  - Ubuntu
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - yarn global add tfx-cli
  - yarn global add typescript
build: off
build_script:
  - lerna bootstrap
  - lerna run build
  - tfx extension create --manifest-globs adopt-openjdk-installer.json
test_script:
  - lerna run test
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: '**\*.vsix'
    name: vsix
matrix:
  fast_finish: true
