name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Install
        run: |
          npm install --global yarn
          yarn --version
          yarn global bin
          yarn global add tfx-cli
          yarn global add typescript
          yarn global add lerna
      - name: Build
        run: |
          export PATH="$(yarn global bin):$PATH"
          lerna bootstrap
          lerna run build
          tfx extension create --manifest-globs adopt-openjdk-installer.json
      - name: Test
        run: |
          lerna run test
      - uses: actions/upload-artifact@v2
        with:
          path: "**/*.vsix"
          if-no-files-found: error
